# Generated by Django 4.2 on 2023-04-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="title",
            new_name="name",
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[
                    ("Home", "Home"),
                    ("Trip", "Trip"),
                    ("Couple", "Couple"),
                    ("Other", "Other"),
                ],
                default="Trip",
                max_length=8,
            ),
        ),
    ]
