# Generated by Django 4.2 on 2023-04-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0002_rename_title_group_name_alter_group_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="group-images"),
        ),
    ]
