# Generated by Django 4.2 on 2023-04-20 13:15

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_group_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="a",
                editable=False,
                max_length=300,
                populate_from="name",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[
                    ("Home", "Home"),
                    ("Trip", "Trip"),
                    ("Couple", "Couple"),
                    ("Other", "Other"),
                ],
                default="Home",
                max_length=8,
            ),
        ),
    ]
