# Generated by Django 4.2 on 2023-04-20 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_group_slug_alter_group_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cost",
            name="time",
        ),
        migrations.AddField(
            model_name="cost",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cost",
            name="group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="costs_set",
                to="website.group",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cost",
            name="image",
            field=models.ImageField(default="mio", upload_to="cost-images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cost",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cost",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cost",
            name="paid_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_costs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
