# Generated by Django 4.2 on 2023-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_remove_cost_time_cost_date_cost_group_cost_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cost-images"),
        ),
    ]
