# Generated by Django 4.2 on 2023-05-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
