# Generated by Django 4.2 on 2023-06-03 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_user_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cost',
            name='members',
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.AddField(
            model_name='costmember',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_set', to='website.cost'),
        ),
        migrations.AddField(
            model_name='costmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_members_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
