# Generated by Django 4.2 on 2023-06-06 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_user_credit_remove_user_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
