from .register_view import RegisterView
from .login_view import LoginView
from .logout_view import LogoutView
from .dashboard_view import DashboardView
from .friend_view import FriendRequestCreationView
from .friend_view import FriendListView
from .friend_view import FriendRequestCancelView
from .friend_view import FriendRequestAcceptView
from .friend_view import FriendRequestRejectView
from .group_view import GroupCreationView
from .group_view import GroupDetailView
from .cost_view import CostCreationView
